export const company= {
    "name":"#companyName",
    "address":"#Address",
    "location":"#Location",
    "website":"#website",
    "industry":"#industry",
    "organizationSize":"#organizationSize",
    "organizationType":"#organizationType",
    "uploadButton":"label[for='logoUpload']",
    "reset":"button[type='reset']",
    "image":"img[alt='Logo Preview']",
    "uploadImage":'input[type="file"]',
    "imagePreview":"img[alt='Logo Preview']",
    "tagline":"#tagline",
    "checkbox":"#checkbox",
    "createProfile":".justify-end",
    "actualName":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > h1:nth-child(1)",
    "actualIndustry":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(2) > p:nth-child(1)",
    "actualLocation":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(2) > p:nth-child(2)",
    "followers":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(2) > p:nth-child(3)",
    "actualSize":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(2) > p:nth-child(4)",
    "postJob":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(3) > button:nth-child(1)",
    "viewCompany":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(3) > button:nth-child(2)",
    "feed":"#Feed-tab",
    "jobs":"#Jobs-tab",
    "analytics":"#Analytics-tab",
    "editInfo":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > button:nth-child(2)",
    "updateInfo":"button[class='bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700']",
    "jobTitle":"#jobTitle",
    "company":"#company",
    "continueOnMyOwn":"button[class='w-full py-3 font-semibold text-[#0a66c2] border border-[#0a66c2] rounded-full bg-transparent hover:border-[#004182] hover:border-2 hover:bg-[#ebf4fd] focus:ring-2 focus:ring-offset-2 focus:ring-[#004182] transition ease-in-out duration-150']",
    "editJobRequirements":"button[aria-label='Edit job details']",
    "editJobType":"#editJobType",
    "cancel":"button[class='py-1 px-3 border border-gray-400 rounded-md text-sm text-gray-700 hover:bg-gray-100']",
    "continue":"button[class='py-2 px-6 border border-transparent rounded-full text-sm font-semibold text-white bg-[#0a66c2] hover:bg-[#004182] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#004182] transition ease-in-out']",
    "editScreening":"button[aria-label='Edit Screening questions']",
    "degreeQuestion":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > label:nth-child(1) > input:nth-child(1)",
    "mustHaveQualification":"input[type='checkbox']",
    "cancelScreening":"button[class='text-gray-500 hover:text-gray-700 text-sm font-medium']",
    "continuetwo":"button[class='py-2 px-6 border border-transparent rounded-full text-sm font-semibold text-white bg-[#0a66c2] hover:bg-[#004182] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#004182] transition ease-in-out']",
    "addScreeningQustion":"button[class='flex items-center text-blue-700 hover:underline text-sm font-medium mt-4']",
    "backgrounsCheck":"div[class='grid grid-cols-2 md:grid-cols-3 gap-3 mt-4'] button:nth-child(1)",
    "mustHaveCheck":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(4) > div:nth-child(1) > div:nth-child(3) > input:nth-child(1)",
    "continuethree":"button[class='py-2 px-6 border border-transparent rounded-full text-sm font-semibold text-white bg-[#0a66c2] hover:bg-[#004182] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#004182] transition ease-in-out']",
    "actualedAnswer":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > span:nth-child(1) > span:nth-child(1)",
    "actualbackAnswer":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > span:nth-child(1) > span:nth-child(1)",
    "actualJobTitle":".text-base.font-semibold.text-gray-800.truncate",
    "applyJob":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > button:nth-child(1)",
    "applyjob2":":nth-child(3) > .justify-between > .flex-col > .bg-blue-600",
    "email":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > input:nth-child(2)",
    "phoneNumber":":nth-child(6) > .fixed > .min-h-screen > .max-w-2xl > :nth-child(2) > .space-y-6 > .space-y-4 > :nth-child(2) > .mt-1 > .block",
    "firstNext":":nth-child(6) > .fixed > .min-h-screen > .max-w-2xl > .justify-end > .bg-blue-600",
    "educationField":".space-y-6 > div > .mt-1",
    "backgroundCheckField":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > textarea:nth-child(2)",
    "submit":":nth-child(6) > .fixed > .min-h-screen > .max-w-2xl > .justify-end > .bg-blue-600",
    "manageJob":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > button:nth-child(2)",
    "manageJob2":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(6) > div:nth-child(1) > button:nth-child(2)",
    "status":"div[class='divide-y divide-gray-200'] div:nth-child(2) div:nth-child(2) div:nth-child(4)",
    "applicantCount":".text-lg.font-semibold.text-gray-800",
    "showasAdmin":".px-5 > .gap-4 > :nth-child(2)",
    "acceptTest":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > button:nth-child(2)",
    "manageAccept":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > button:nth-child(2)",
    "clickApplicant":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1)",
    "acceptmessage":"",
    "firstDate":":nth-child(1) > .react-datepicker__input-container > .p-2",
    "lastDate":":nth-child(3) > .react-datepicker__input-container > .p-2",
    "totalFollowers":".bg-purple-50 > .flex > :nth-child(1) > .text-3xl",
}

export const messaging={
    "messagingIcon":'.mr-27 > :nth-child(4) > .flex',
    "searchConnections":"input[placeholder='Search connections...']",
    "connectionSuggestions":".absolute.top-full.left-0.right-0.mt-1.bg-white.border.rounded-md.shadow-lg.max-h-60.overflow-y-auto.z-20",
    "textArea":"textarea[placeholder='Write a message...']",
    "sendMessage":"button[title='Send message']",
    "messageList":".flex-col > .relative > .whitespace-pre-wrap",
    "lastMessage":".text-sm.text-gray-600.truncate",
    "chatList":"div[class='flex-grow overflow-y-auto']",
    "newChat1":".font-semibold.truncate.text-gray-800",
    "unreadIcon":".bg-blue-500",
    "firstchat":"div[role='button']",
    "dots":"button[aria-label='Conversation options']",
    "markasUnread":"button[role='menuitem']",
    "blockOldUser":"button[title='Block Leonel Schuppe']",
    "blockText":".p-4.text-center.bg-yellow-100.text-yellow-800.text-sm",
    "unblock":"button[class='ml-2 font-semibold text-yellow-900 hover:underline']",
    "blockNew":".p-3 > .p-2",
    "attachFile":"button[title='Attach file']",
    "messageHistory":".items-end > .max-w-md > .flex-col > .relative > .w-40"
}

export const jobs={
    "jobIcon":".mr-27 > :nth-child(3) > .flex",
    "saveJob":"button[class='mt-4 bg-blue-600 text-white px-4 py-2 rounded-full hover:bg-blue-700']",
    "myJobs":"button[class='flex items-center gap-3 font-semibold w-full text-left py-3 px-6 hover:bg-gray-100']",
    "deleteFirst":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(3) > div:nth-child(1) > button:nth-child(3)",
    "firstJob":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > p:nth-child(1)",
    "apply":".mr-4",
    "email":"#email",
    "countryCode":"#countryCode",
    "egypt":"",
    "mobile":"#mobile",
    "next1":".mt-6 > .rounded-md",
    "onsite":"input[placeholder='Your answer'][name='question-67f7d1bc0efab7e413e580a4']",
    "expertise":"input[placeholder='Your answer'][name='question-67f7d1bc0efab7e413e580a3']",
    "remote":"input[placeholder='Your answer'][name='question-67f7d1bc0efab7e413e580a1']",
    "customQuestion":"input[placeholder='Your answer'][name='question-67f7d1bc0efab7e413e580a2']",
    "apply":".mt-6 > .rounded-md",
    "pending":"button[class='px-4 py-2 rounded-full text-sm border bg-[#01754f] text-white font-semibold hover:bg-[#004c33]']",
    "searchIndustry":".max-w-xl > :nth-child(1) > .text-sm",
    "filterByCompany":".flex-wrap > :nth-child(3) > .text-sm",
    "filteredcompany":":nth-child(3) > .flex > .flex-1 > .text-gray-700",
    "postfreeJob":"button[class='flex items-center gap-3 w-full font-semibold text-left p-5 text-blue-600 hover:bg-gray-100 rounded-md']",
    "postedJobs":".flex.justify-between.items-center.p-2.cursor-pointer.text-gray-700",
    "postedJobsText":"div[class='flex-1 bg-white pt-6 pb-6 mx-4 rounded-lg shadow-md'] div:nth-child(2) div:nth-child(1) p:nth-child(1)",
    "applicant":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2)",
    "messageButton":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(4) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > button:nth-child(1)",
    "acceptapplicant":"",
    "acceptedTab":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(2) > button:nth-child(4)",
    "postedjobslist":".flex-1 > .cursor-pointer",
}

export const feed={
    "createPost":"button[class='text-[rgba(0,0,0,0.6)] outline-none min-h-[48px] leading-1.5 text-sm font-semibold flex items-center p-2 pl-4 flex-grow border border-[rgba(0,0,0,0.15)] rounded-[35px] cursor-pointer hover:bg-[rgba(0,0,0,0.08)] text-left']",
    "textArea":"textarea[placeholder='What do you want to talk about?']",
    "postButton":"button[class='text-white font-semibold px-4 py-1.5 rounded-full bg-[#0a66c2] hover:bg-[#084482]']",
    "addImage":".border-t > .flex > :nth-child(1)",
    "uploadImage":'input[type="file"]',
    "likeButton":":nth-child(2) > .px-4 > .relative > .outline-none > span",
    "commentButton":":nth-child(2) > .px-4 > :nth-child(2)",
    "commentTextArea":"textarea[placeholder='Add a comment...']",
    "imagetoComment":"button[title='Add photo']",
    "postComment":".flex-1 > .justify-between > .text-sm",
    "commentCount":":nth-child(2) > .mx-4 > :nth-child(2) > p",
    "postToHide":"body div article:nth-child(2)",
    "postMenu":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > article:nth-child(3) > div:nth-child(1) > div:nth-child(2) > button:nth-child(1)",
    "hidePost":"body div div div div div div div div li:nth-child(1)",
    "likedPopup":"div[class='bg-white rounded-lg w-full max-w-md max-h-[80vh] overflow-hidden']",
    "postDoc":'body div div div div div div div div div div:nth-child(1) button:nth-child(3)',
    "likeComment":".space-x-3 > div.flex > .relative > .outline-none",
    "actualcomment":":nth-child(5) > .flex-1 > .bg-\[\#f3f2ef\] > .mt-1",
}

export const Signup={
    "joinLink":"a[class='text-gray-700 text-sm font-semibold hover:underline']",
    "FName":"#first-name",
    "LName":"#last-name",
    "Email":"#email",
    "Password":"#password",
    "submitMP":"button[type='submit']",
    "emailExistsPopup":":nth-child(2) > .go4109123758 > .go2072408551 > .go3958317564",
    "errorMessage":".text-xs.text-red-500.mt-1",
    "passwordError":"div[class='relative flex flex-col'] p[class='text-xs text-red-500 mt-1']",
    "google":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > button:nth-child(3)",
    "emptyEmail":":nth-child(2) > .go4109123758 > .go2072408551",
}

export const Login={
    "signinButton":"a[class='text-blue-600 text-sm font-semibold border border-blue-600 px-4 py-2 rounded-full hover:bg-blue-100']",
    "email":"input[placeholder='Email']",
    "password":"input[placeholder='Password']",
    "submit":"button[type='submit']",
}


export const notifications={
    "badgeCount":"div[class='absolute -top-1 -right-1 bg-[#cb112d] text-white rounded-full w-5 h-5 flex items-center justify-center text-xs font-medium']",
    "notificationsCard":"div[class='bg-white shadow-sm rounded-lg border border-gray-300']",
    "unread":"#Mark-Read > #Notification-Click > .w-2.h-2.bg-blue-600.rounded-full.mt-2",
    "currentUnreadItem":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)",
    "notificationsIcon":"button[class='hover:bg-gray-200 p-2 rounded-lg relative']",
    "pushNotifications":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)",
    "send":".mb-4",
    "jobsTab":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > button:nth-child(1)",
    "postsTab":"#Post-Tabs",
    "mentionsTab":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(4) > button:nth-child(1)",
}

export const admin={
    "reportsIcon":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(2) > a:nth-child(1)",
    "reportsCard":"body div div div div div div li",
    "takeAction":".md\:flex-row > .bg-gray-50 > .flex-col > .text-white",
    "actionedButton":"button:nth-child(4)",
    "dismissedButton":"button[class='inline-flex items-center px-4 py-2 text-sm font-medium rounded-r-md border-t border-b border-r bg-white text-gray-700 hover:bg-gray-50']",
    "activeJobsCount":"div[class='grid grid-cols-1 md:grid-cols-4 gap-4 mb-6'] div:nth-child(1) div:nth-child(1) div:nth-child(2) p:nth-child(2)",

    "jobListingsIcon":":nth-child(3) > .flex",
    "flaggedJobsCount":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(4) > div:nth-child(1) > div:nth-child(2) > p:nth-child(2)",


}

export const profile={
    "editName":"button[aria-label='Edit name']",
    "firstName":"#firstName",
    "lastName":"#lastName",
    "tryPremium":"button[class='bg-amber-500 text-white py-2 px-6 rounded-full font-medium hover:bg-amber-600 transition-colors shadow-md']",
    "saveName":"#updateButton",
    "name":".text-2xl.font-bold.flex.items-center",
    "editAbout":"button[class='text-[#0073b1] hover:text-gray-700']",
    "aboutDescription":"textarea[placeholder='Tell us about yourself...']",
    "aboutPhone":"input[placeholder='Your phone number']",
    "aboutPhoneType":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > form:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > select:nth-child(2)",
    "aboutAddress":"input[placeholder='Your address']",
    "aboutWebsite":"input[placeholder='https://example.com']",
    "aboutWebsiteType":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > form:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > select:nth-child(2)",
    "finalDescription":".text-gray-700.whitespace-pre-wrap",
    "finalPhone":"div[class='flex items-center space-x-2'] div p[class='text-sm font-medium text-[#676767]']",
    "finalPhoneType":"p[class='text-sm text-[#676767] font-extralight']",
    "finalAddress":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > p:nth-child(2)",
    "finalWebsite":"p[class='font-medium']",
    "finalWebsiteTypeabout":".flex-col > :nth-child(2) > div > .text-sm",
    //experience
    "save":"button[type='submit']",
    "phone":"input[placeholder='Your phone number']",
    "phoneType":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > form:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > select:nth-child(2)",
    "address":"input[placeholder='Your address']",
    "birthDay":"div[class='flex gap-2'] select:nth-child(1)",
    "birthMonth":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > form:nth-child(2) > div:nth-child(1) > div:nth-child(4) > div:nth-child(2) > select:nth-child(2)",
    "websiteURL":"input[placeholder='https://example.com']",
    "websiteType":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > form:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > select:nth-child(2)",
    //"finalPhone":".justify-between > :nth-child(1) > div > .font-medium",
    // "finalPhoneType":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > p:nth-child(2)",
    // "finalAddress":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > p:nth-child(2)",
    // "finalDate":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(3) > p:nth-child(2)",
    // "finalWebsite":".flex-col > :nth-child(2) > div > .font-medium",
    "finalWebsiteType":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(4) > div:nth-child(2) > p:nth-child(2)",
    "urlError":".text-red-500.text-xs.mt-1",
    "CancelURL":"button[class='px-4 py-2 border border-gray-300 rounded hover:bg-gray-100']",
    "addExperience":"button[title='Add experience']",
    "jobTitle":"#jobTitle",
    "company":"#company",
    "employmentType":"#employmentType",
    "location":"#location",
    "locationType":"#locationType",
    "startMonth":":nth-child(1) > .grid > :nth-child(1) > .w-full",
    "startYear":"select[name='fromYear']",
    "currentlyWorking":"#currentlyWorking",
    "jobDescription":"#description",
    "javascript":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(8) > div:nth-child(4) > div:nth-child(2) > button:nth-child(2)",
    "jobSkill":"input[placeholder='Add a skill']",
    "addJobSkill":"button[class='bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700']",
    "media":"#media",
    "foundVia":"#foundVia",
    "saveExperience":"button[class='px-6 py-2 bg-blue-600 text-white rounded-md font-medium hover:bg-blue-700']",
    "done":"button[class='flex-1 px-4 py-2 rounded-full font-medium border border-gray-300 text-gray-700 hover:bg-gray-50']",
    "expOkay":".bg-white > .flex-col > .w-full > :nth-child(3)",
    "newJobTitle":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > h3:nth-child(1)",
    "newCompany":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > p:nth-child(2)",
    "newJobType":":nth-child(2) > .flex-1 > :nth-child(3)",
    "newLocation":":nth-child(2) > .flex-1 > :nth-child(4)",
    "newDate":":nth-child(2) > .flex-1 > :nth-child(5)",
    "newDescription":"p.text-gray-600.mt-1.text-sm",
    "newFoundVia":"p.text-gray-500.text-sm",
    //education
    "newEducation":"button[title='Add education']",
    "school":".space-y-4 > :nth-child(1) > .w-full",
    "degree":".space-y-4 > :nth-child(2) > .w-full",
    "fieldOfStudy":".space-y-4 > :nth-child(3) > .w-full",
    "startMonthe":":nth-child(4) > .grid > :nth-child(1) > .w-full",
    "startYeare":":nth-child(4) > .grid > :nth-child(2) > .w-full",
    "currentlyStudying":"#currentlyStudying",
    "grade":"input[placeholder='Ex: 3.8 GPA']",
    "activities":"textarea[placeholder='Ex: Coding Club, Debate Team']",
    "educationDescription":"textarea[placeholder='You can write about projects, achievements, etc.']",
    "saveEd":"button[class='px-6 py-2 bg-blue-600 text-white rounded-full font-medium hover:bg-blue-700']",
    "edOkay":"button[class='flex-1 px-4 py-2 rounded-full font-medium border border-gray-300 text-gray-700 hover:bg-gray-50']",
    "actualSchool":":nth-child(3) > .bg-white > .space-y-4 > :nth-child(2) > .flex-1 > .justify-between > .font-medium",
    "actualDegreeandField":":nth-child(3) > .bg-white > .space-y-4 > :nth-child(2) > .flex-1 > :nth-child(2)",
    "actualDate":":nth-child(3) > .bg-white > .space-y-4 > :nth-child(2) > .flex-1 > :nth-child(3)",
    "actualGrade":":nth-child(2) > .flex-1 > .text-gray-500.mt-1",
    "actualDescription":":nth-child(3) > .bg-white > .space-y-4 > :nth-child(2) > .flex-1 > .text-gray-600.mt-1",
    "edOkay":".bg-white > .flex-col > .w-full > :nth-child(3)",
    //skills
    "addSkills":"button[title='Add skill']",
    "writeSkill":"input[placeholder='Ex: JavaScript, Project Management, Photoshop']",
    "commonSkill":"body div form div div button:nth-child(2)",
    "addedSkill":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(4) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > h3:nth-child(1)",
    "endorse":":nth-child(3) > .justify-between > :nth-child(1) > div.mt-2 > .mt-2",
    "endorsmentCount":":nth-child(3) > .justify-between > :nth-child(1) > div.mt-2 > .flex > .text-blue-600",
    "endorser":".font-medium.text-gray-800.text-sm",
    "visibilityText":".text-blue-800",
    "searchName":"div[class='flex items-center bg-[#edf3f8] rounded-sm ml-2 w-90'] input[placeholder='Search']",

}

export const settings={
    "visibility":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > select:nth-child(1)",
}