export const company= {
    "name":"#companyName",
    "address":"#Address",
    "website":"#website",
    "industry":"#industry",
    "organizationSize":"#organizationSize",
    "organizationType":"#organizationType",
    "uploadButton":"label[for='logoUpload']",
    "reset":"button[type='reset']",
    "image":"img[alt='Logo Preview']",
    "uploadImage":'input[type="file"]',
    "imagePreview":"img[alt='Logo Preview']",
    "tagline":"#tagline",
    "checkbox":"#checkbox",
    "createProfile":"body div div div div div button:nth-child(1)",
}

export const messaging={
    "messagingIcon":"img[alt='Messaging']",
    "searchConnections":"input[placeholder='Search connections...']",
    "connectionSuggestions":".absolute.top-full.left-0.right-0.mt-1.bg-white.border.rounded-md.shadow-lg.max-h-60.overflow-y-auto.z-20",
    "textArea":"textarea[placeholder='Write a message...']",
    "sendMessage":"button[title='Send message']",
    "messageList":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2)",
    "lastMessage":".text-sm.text-gray-600.truncate",
    "chatList":"div[class='flex-grow overflow-y-auto']",
    "newChat1":".font-semibold.truncate.text-gray-800",
    "unreadIcon":"div:nth-child(49) div:nth-child(1) div:nth-child(1) p:nth-child(2)",
    "firstchat":"div[role='button']",
    "dots":"button[aria-label='Conversation options']",
    "markasUnread":"button[role='menuitem']",
    "blockOldUser":"button[title='Block Ibrahim Muhammed']",
    "blockText":".p-4.text-center.bg-yellow-100.text-yellow-800.text-sm",
    "unblock":"button[class='ml-2 font-semibold text-yellow-900 hover:underline']",
    "blockNew":"button[title='Block Ali Abdelghani']",
    "attachFile":"button[title='Attach file']",
}

export const jobs={
    "jobIcon":"img[alt='Jobs']",
    "saveJob":"button[class='mt-4 bg-blue-600 text-white px-4 py-2 rounded-full hover:bg-blue-700']",
    "myJobs":"button[class='flex items-center gap-3 font-semibold w-full text-left py-3 px-6 hover:bg-gray-100']",
    "deleteFirst":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(3) > div:nth-child(1) > button:nth-child(3)",
    "firstJob":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > p:nth-child(1)",
    "apply":".mr-4",
    "email":"#email",
    "countryCode":"#countryCode",
    "egypt":"",
    "mobile":"#mobile",
    "next1":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(6) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(5) > button:nth-child(1)",
    "onsite":"input[placeholder='Your answer'][name='question-67f7d1bc0efab7e413e580a4']",
    "expertise":"input[placeholder='Your answer'][name='question-67f7d1bc0efab7e413e580a3']",
    "remote":"input[placeholder='Your answer'][name='question-67f7d1bc0efab7e413e580a1']",
    "customQuestion":"input[placeholder='Your answer'][name='question-67f7d1bc0efab7e413e580a2']",
    "apply":"button[class='rounded-md bg-blue-600 px-6 py-2 text-sm font-semibold text-white shadow-sm hover:bg-blue-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600']",
    "pending":"button[class='px-4 py-2 rounded-full text-sm border bg-[#01754f] text-white font-semibold hover:bg-[#004c33]']",
    "searchIndustry":"input[placeholder='Title, skill or company']",
}

export const feed={
    "createPost":"button[class='text-[rgba(0,0,0,0.6)] outline-none min-h-[48px] leading-1.5 text-sm font-semibold flex items-center p-2 pl-4 flex-grow border border-[rgba(0,0,0,0.15)] rounded-[35px] cursor-pointer hover:bg-[rgba(0,0,0,0.08)] text-left']",
    "textArea":"textarea[placeholder='What do you want to talk about?']",
    "postButton":"button[class='text-white font-semibold px-4 py-1.5 rounded-full bg-[#0a66c2] hover:bg-[#084482]']",
    "addImage":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(5) > div:nth-child(1) > button:nth-child(1)",
    "uploadImage":'input[type="file"]',
    "likeButton":":nth-child(2) > .px-4 > .relative > .outline-none > span",
    "commentButton":":nth-child(2) > .px-4 > :nth-child(2)",
    "commentTextArea":"textarea[placeholder='Add a comment...']",
    "imagetoComment":"button[title='Add photo']",
    "postComment":"button[class='text-sm font-semibold px-3 py-1 rounded-full bg-[#0a66c2] text-white hover:bg-[#084482]']",
    "commentCount":":nth-child(2) > .mx-4 > :nth-child(2) > p",
    "postToHide":"body div article:nth-child(2)",
    "postMenu":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > article:nth-child(3) > div:nth-child(1) > div:nth-child(2) > button:nth-child(1)",
    "hidePost":"body div div div div div div div div li:nth-child(1)",
}

export const Signup={
    "joinLink":"a[class='text-gray-700 text-sm font-semibold hover:underline']",
    "FName":"#first-name",
    "LName":"#last-name",
    "Email":"#email",
    "Password":"#password",
    "submitMP":"button[type='submit']",
    "emailExistsPopup":":nth-child(1) > :nth-child(2) > .go4109123758 > .go2072408551 > .go3958317564",
    "errorMessage":".text-xs.text-red-500.mt-1",
    "passwordError":"div[class='relative flex flex-col'] p[class='text-xs text-red-500 mt-1']",
    "google":"body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > button:nth-child(3)",
    "emptyEmail":":nth-child(2) > .go4109123758 > .go2072408551",
}

export const Login={
    "signinButton":"a[class='text-blue-600 text-sm font-semibold border border-blue-600 px-4 py-2 rounded-full hover:bg-blue-100']",
    "email":"input[placeholder='Email']",
    "password":"input[placeholder='Password']",
    "submit":"button[type='submit']",
}